/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Acneplan6h3v9k2sRouteImport } from './routes/acneplan-6h3v9k2s'
import { Route as Bpsa4k7m2q9xRouteImport } from './routes/bpsa-4k7m2q9x'
import { Route as Dspot5c9j4w7tRouteImport } from './routes/dspot-5c9j4w7t'
import { Route as Hairbo2z6d8f3yRouteImport } from './routes/hairbo-2z6d8f3y'
import { Route as Trtaza8v3n6r1pRouteImport } from './routes/trtaza-8v3n6r1p'

const Acneplan6h3v9k2sRoute = Acneplan6h3v9k2sRouteImport.update({
  id: '/acneplan-6h3v9k2s',
  path: '/acneplan-6h3v9k2s',
  getParentRoute: () => rootRouteImport,
} as any)
const Bpsa4k7m2q9xRoute = Bpsa4k7m2q9xRouteImport.update({
  id: '/bpsa-4k7m2q9x',
  path: '/bpsa-4k7m2q9x',
  getParentRoute: () => rootRouteImport,
} as any)
const Dspot5c9j4w7tRoute = Dspot5c9j4w7tRouteImport.update({
  id: '/dspot-5c9j4w7t',
  path: '/dspot-5c9j4w7t',
  getParentRoute: () => rootRouteImport,
} as any)
const Hairbo2z6d8f3yRoute = Hairbo2z6d8f3yRouteImport.update({
  id: '/hairbo-2z6d8f3y',
  path: '/hairbo-2z6d8f3y',
  getParentRoute: () => rootRouteImport,
} as any)
const Trtaza8v3n6r1pRoute = Trtaza8v3n6r1pRouteImport.update({
  id: '/trtaza-8v3n6r1p',
  path: '/trtaza-8v3n6r1p',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/acneplan-6h3v9k2s': typeof Acneplan6h3v9k2sRoute
  '/bpsa-4k7m2q9x': typeof Bpsa4k7m2q9xRoute
  '/dspot-5c9j4w7t': typeof Dspot5c9j4w7tRoute
  '/hairbo-2z6d8f3y': typeof Hairbo2z6d8f3yRoute
  '/trtaza-8v3n6r1p': typeof Trtaza8v3n6r1pRoute
}
export interface FileRoutesByTo {
  '/acneplan-6h3v9k2s': typeof Acneplan6h3v9k2sRoute
  '/bpsa-4k7m2q9x': typeof Bpsa4k7m2q9xRoute
  '/dspot-5c9j4w7t': typeof Dspot5c9j4w7tRoute
  '/hairbo-2z6d8f3y': typeof Hairbo2z6d8f3yRoute
  '/trtaza-8v3n6r1p': typeof Trtaza8v3n6r1pRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/acneplan-6h3v9k2s': typeof Acneplan6h3v9k2sRoute
  '/bpsa-4k7m2q9x': typeof Bpsa4k7m2q9xRoute
  '/dspot-5c9j4w7t': typeof Dspot5c9j4w7tRoute
  '/hairbo-2z6d8f3y': typeof Hairbo2z6d8f3yRoute
  '/trtaza-8v3n6r1p': typeof Trtaza8v3n6r1pRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/acneplan-6h3v9k2s'
    | '/bpsa-4k7m2q9x'
    | '/dspot-5c9j4w7t'
    | '/hairbo-2z6d8f3y'
    | '/trtaza-8v3n6r1p'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/acneplan-6h3v9k2s'
    | '/bpsa-4k7m2q9x'
    | '/dspot-5c9j4w7t'
    | '/hairbo-2z6d8f3y'
    | '/trtaza-8v3n6r1p'
  id:
    | '__root__'
    | '/acneplan-6h3v9k2s'
    | '/bpsa-4k7m2q9x'
    | '/dspot-5c9j4w7t'
    | '/hairbo-2z6d8f3y'
    | '/trtaza-8v3n6r1p'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Acneplan6h3v9k2sRoute: typeof Acneplan6h3v9k2sRoute
  Bpsa4k7m2q9xRoute: typeof Bpsa4k7m2q9xRoute
  Dspot5c9j4w7tRoute: typeof Dspot5c9j4w7tRoute
  Hairbo2z6d8f3yRoute: typeof Hairbo2z6d8f3yRoute
  Trtaza8v3n6r1pRoute: typeof Trtaza8v3n6r1pRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/acneplan-6h3v9k2s': {
      id: '/acneplan-6h3v9k2s'
      path: '/acneplan-6h3v9k2s'
      fullPath: '/acneplan-6h3v9k2s'
      preLoaderRoute: typeof Acneplan6h3v9k2sRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpsa-4k7m2q9x': {
      id: '/bpsa-4k7m2q9x'
      path: '/bpsa-4k7m2q9x'
      fullPath: '/bpsa-4k7m2q9x'
      preLoaderRoute: typeof Bpsa4k7m2q9xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dspot-5c9j4w7t': {
      id: '/dspot-5c9j4w7t'
      path: '/dspot-5c9j4w7t'
      fullPath: '/dspot-5c9j4w7t'
      preLoaderRoute: typeof Dspot5c9j4w7tRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hairbo-2z6d8f3y': {
      id: '/hairbo-2z6d8f3y'
      path: '/hairbo-2z6d8f3y'
      fullPath: '/hairbo-2z6d8f3y'
      preLoaderRoute: typeof Hairbo2z6d8f3yRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trtaza-8v3n6r1p': {
      id: '/trtaza-8v3n6r1p'
      path: '/trtaza-8v3n6r1p'
      fullPath: '/trtaza-8v3n6r1p'
      preLoaderRoute: typeof Trtaza8v3n6r1pRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Acneplan6h3v9k2sRoute: Acneplan6h3v9k2sRoute,
  Bpsa4k7m2q9xRoute: Bpsa4k7m2q9xRoute,
  Dspot5c9j4w7tRoute: Dspot5c9j4w7tRoute,
  Hairbo2z6d8f3yRoute: Hairbo2z6d8f3yRoute,
  Trtaza8v3n6r1pRoute: Trtaza8v3n6r1pRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
